apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - ./mongo-express/deployment.yaml
  - ./mongo-express/service.yaml
  - ./mongo-express/config.yaml

generators:
  - ./secret-generator.yaml
