apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  # Specify a name
  name: secrets-generator
  annotations:
    config.kubernetes.io/function: |
        exec:
          # if the binary is in your PATH, you can do
          # path: ksops
          # otherwise, path should be relative to manifest files, like
          path: ksops
files:
  - ./secrets.enc.yaml
